### ISSUE TITLE
Better Tag NBT Tips is excluded from the CurseForge API

### ISSUE THREAD

**Issue by ishihara1989** [GregTechCEu/GregTech-Modern-Community-Pack#57]
When executing start.ps1, the server failed to start and the following log is produced:
```
> .\start.ps1
Clearing potentially incorrect versions of the FindMe mod...
Fetching the FindMe mod...
Updating the server pack...
Server installation/update failed with exit code 1.
```

When running each command in start.ps1 manually, the error occurs at the command:
`java -jar "packwiz-installer-bootstrap.jar" -g -s server $PACK_URI`

The output is:

```
> java -jar "packwiz-installer-bootstrap.jar" -g -s server $PACK_URI
Current version is: v0.5.14
New version is: v0.5.14
Already up to date!
Loading manifest file...
Loading pack file...
Loading MultiMC pack file...
MultiMC not detected
Checking local files...
Modpack name: GregTech CEu Modern Community Pack
Checking local files...
Comparing new files...
Side changed, invalidating all mods
Validating existing files...
Resolving CurseForge metadata...
Failed to download modpack, the following errors were encountered:
Better Tag NBT Tips: java.lang.Exception: This mod is excluded from the CurseForge API and must be downloaded manually.
Please go to https://www.curseforge.com/minecraft/mc-mods/better-tips-nbt-tag/files/4636196 and save this file to C:\Users\ashit\minecraft\gtm-server-test\mods\BetterTags-1.20.1-1.1.jar
        at link.infra.packwiz.installer.metadata.curseforge.CurseForgeSourcerKt.resolveCfMetadata(SourceFile:151)
        at link.infra.packwiz.installer.UpdateManager.validateAndResolve(SourceFile:448)
        at link.infra.packwiz.installer.UpdateManager.processIndex(SourceFile:350)
        at link.infra.packwiz.installer.UpdateManager.start(SourceFile:178)
        at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:42)
        at link.infra.packwiz.installer.Main.startup(SourceFile:112)
        at link.infra.packwiz.installer.Main.<init>(SourceFile:154)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
        at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
        at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
Better Tag NBT Tips: java.lang.Exception: This mod is excluded from the CurseForge API and must be downloaded manually.
Please go to https://www.curseforge.com/minecraft/mc-mods/better-tips-nbt-tag/files/4636196 and save this file to C:\Users\ashit\minecraft\gtm-server-test\mods\BetterTags-1.20.1-1.1.jar
        at link.infra.packwiz.installer.metadata.curseforge.CurseForgeSourcerKt.resolveCfMetadata(SourceFile:151)
        at link.infra.packwiz.installer.UpdateManager.validateAndResolve(SourceFile:448)
        at link.infra.packwiz.installer.UpdateManager.processIndex(SourceFile:350)
        at link.infra.packwiz.installer.UpdateManager.start(SourceFile:178)
        at link.infra.packwiz.installer.UpdateManager.<init>(SourceFile:42)
        at link.infra.packwiz.installer.Main.startup(SourceFile:112)
        at link.infra.packwiz.installer.Main.<init>(SourceFile:154)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
        at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
        at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
Update cancelled by user!
```

Manual downloading fixed the problem.

It is likely necessary to change the installation method.

**Comment by ursamina** [comment]
fixed by #59
